import React from 'react';
import { Container, Button, Row, Col, Card } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import './Home.css';

// Importing images directly
import style1 from './assets/style1.png';
import style2 from './assets/style2.png';
import style3 from './assets/style3.png';
import style4 from './assets/style4.png';

import sample1 from './assets/sample1.png';
import sample2 from './assets/sample2.png';
import sample3 from './assets/sample3.png';
import sample4 from './assets/sample4.png';

const styles = [
  { name: "Modern", description: "Sophisticated, clean lines, and neutral colors.", image: style1 },
  { name: "Bohemian", description: "Eclectic, vibrant colors with layered textures.", image: style2 },
  { name: "Industrial", description: "Exposed brick and metal with an urban feel.", image: style3 },
  { name: "Minimalist", description: "Simple, peaceful with uncluttered spaces.", image: style4 },
];

const sampleImages = [sample1, sample2, sample3, sample4];

function Home() {
  return (

    <main>
    <Container fluid className="home-container text-center my-5 px-4">
      <Row className="welcome-section">
        <Col lg={10} className="mx-auto">
          <h1 className="main-title">Welcome to the Interior Design Generator</h1>
          <p className="sub-title">Transform your photos into stunning designs using AI. Upload an image, choose a style, and let the magic happen!</p>
          <Button variant="primary" as={Link} to="/generate" className="cta-button">
            Get Started
          </Button>
        </Col>
      </Row>

      <section className="styles-section">
        <h2 className="section-title">Explore Our Styles</h2>
        <Row className="styles-row">
          {styles.map((style, index) => (
            <Col md={3} key={index} className="mb-4">
              <Card className="style-card shadow-sm">
                <Card.Img variant="top" src={style.image} alt={style.name} className="style-image" />
                <Card.Body>
                  <Card.Title className="style-title">{style.name}</Card.Title>
                  <Card.Text className="style-description">{style.description}</Card.Text>
                </Card.Body>
              </Card>
            </Col>
          ))}
        </Row>
      </section>

      <section className="samples-section">
        <h2 className="section-title">Sample Designs Generated by AI</h2>
        <Row className="samples-row">
          {sampleImages.map((image, index) => (
            <Col md={3} key={index} className="mb-4">
              <Card className="sample-card shadow-sm">
                <Card.Img variant="top" src={image} alt={`Sample ${index + 1}`} className="sample-image" />
              </Card>
            </Col>
          ))}
        </Row>
      </section>


    </Container>

<footer className="footer mt-5 py-4">
<Container>
  <Row>
    <Col>
      <p className="footer-text">&copy; {new Date().getFullYear()} Interior Design Generator. All rights reserved.</p>
      <p className="footer-social">Follow us for more inspiration!</p>
    </Col>
  </Row>
</Container>
</footer>


</main>
  );
}

export default Home;
